os:
  - Visual Studio 2015

platform: x64
  - x64

branches:
  only:
    - master
   
install:
  - cinst cmake

build:
  verbosity: detailed

configuration:
  - Debug
  
environment:
  matrix:
    - env_arch: "x64"
      Qt5_DIR: C:\Qt\5.8\msvc2015_64
      Qt5Core_DIR: C:\Qt\5.8\msvc2015_64
    - env_arch: "x86"
      Qt5_DIR: C:\Qt\5.8\msvc2015
      Qt5Core_DIR: C:\Qt\5.8\msvc2015

before_build:
  - set PATH=%PATH%;C:\Program Files\CMake\bin
  - set PATH=%PATH%;%Qt5_DIR%\bin;%Qt5_DIR%\lib\cmake
  
build_script:
  - cmake --version
  - mkdir build
  - cd build
  - if [%env_arch%]==[x64] (
      cmake .. -A x64 )
  - if [%env_arch%]==[x86] (
      cmake .. )
  - cmake --build .
  - cd ..
