language: cpp
sudo: true

install:
  - sudo apt-get update
  - sudo apt-get install qt5-default qt5-qmake

before_script:
  - cmake --version

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - cd ..

compiler:
  - gcc
os:
  - linux
  
