language: cpp
sudo: true

os:
  - linux
  - osx
  
compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - qt5-default
      - qt5-qmake
      
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt5 ; fi
  
before_script:
  - cmake --version

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - cd ..
