language: cpp
sudo: true

os:
  - linux
  - osx
    
compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - cmake
      - qt5-default
      - qt5-qmake

before_script:
  - cmake --version
  - qmake -v

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - cd ..
